# for development

version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 86:80
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "my_database"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
